// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xheap_sort.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHeap_sort_CfgInitialize(XHeap_sort *InstancePtr, XHeap_sort_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XHeap_sort_Start(XHeap_sort *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL) & 0x80;
    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHeap_sort_IsDone(XHeap_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHeap_sort_IsIdle(XHeap_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHeap_sort_IsReady(XHeap_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHeap_sort_EnableAutoRestart(XHeap_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XHeap_sort_DisableAutoRestart(XHeap_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XHeap_sort_Get_array_r_BaseAddress(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE);
}

u32 XHeap_sort_Get_array_r_HighAddress(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH);
}

u32 XHeap_sort_Get_array_r_TotalBytes(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1);
}

u32 XHeap_sort_Get_array_r_BitWidth(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHEAP_SORT_AXILITES_WIDTH_ARRAY_R;
}

u32 XHeap_sort_Get_array_r_Depth(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHEAP_SORT_AXILITES_DEPTH_ARRAY_R;
}

u32 XHeap_sort_Write_array_r_Words(XHeap_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XHeap_sort_Read_array_r_Words(XHeap_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XHeap_sort_Write_array_r_Bytes(XHeap_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XHeap_sort_Read_array_r_Bytes(XHeap_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHEAP_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i);
    }
    return length;
}

u32 XHeap_sort_Get_array_out_BaseAddress(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE);
}

u32 XHeap_sort_Get_array_out_HighAddress(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH);
}

u32 XHeap_sort_Get_array_out_TotalBytes(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1);
}

u32 XHeap_sort_Get_array_out_BitWidth(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHEAP_SORT_AXILITES_WIDTH_ARRAY_OUT;
}

u32 XHeap_sort_Get_array_out_Depth(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHEAP_SORT_AXILITES_DEPTH_ARRAY_OUT;
}

u32 XHeap_sort_Write_array_out_Words(XHeap_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XHeap_sort_Read_array_out_Words(XHeap_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XHeap_sort_Write_array_out_Bytes(XHeap_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XHeap_sort_Read_array_out_Bytes(XHeap_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XHEAP_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i);
    }
    return length;
}

void XHeap_sort_InterruptGlobalEnable(XHeap_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_GIE, 1);
}

void XHeap_sort_InterruptGlobalDisable(XHeap_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_GIE, 0);
}

void XHeap_sort_InterruptEnable(XHeap_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_IER);
    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_IER, Register | Mask);
}

void XHeap_sort_InterruptDisable(XHeap_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_IER);
    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_IER, Register & (~Mask));
}

void XHeap_sort_InterruptClear(XHeap_sort *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHeap_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_ISR, Mask);
}

u32 XHeap_sort_InterruptGetEnabled(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_IER);
}

u32 XHeap_sort_InterruptGetStatus(XHeap_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHeap_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XHEAP_SORT_AXILITES_ADDR_ISR);
}

