// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _heap_sort_swap_hw_HH_
#define _heap_sort_swap_hw_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct heap_sort_swap_hw : public sc_module {
    // Port declarations 4
    sc_in< sc_lv<32> > x_read;
    sc_in< sc_lv<32> > y_read;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;


    // Module declarations
    heap_sort_swap_hw(sc_module_name name);
    SC_HAS_PROCESS(heap_sort_swap_hw);

    ~heap_sort_swap_hw();

    sc_trace_file* mVcdFile;

    static const bool ap_true;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_return_0();
    void thread_ap_return_1();
};

}

using namespace ap_rtl;

#endif
