// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "heap_sort_swap_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool heap_sort_swap_hw::ap_true = true;
const sc_logic heap_sort_swap_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic heap_sort_swap_hw::ap_const_logic_0 = sc_dt::Log_0;

heap_sort_swap_hw::heap_sort_swap_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_return_0);
    sensitive << ( y_read );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( x_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "heap_sort_swap_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, x_read, "(port)x_read");
    sc_trace(mVcdFile, y_read, "(port)y_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif

    }
}

heap_sort_swap_hw::~heap_sort_swap_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void heap_sort_swap_hw::thread_ap_return_0() {
    ap_return_0 = y_read.read();
}

void heap_sort_swap_hw::thread_ap_return_1() {
    ap_return_1 = x_read.read();
}

}

