// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "array_r"
#define AUTOTB_TVIN_array_r  "../tv/cdatafile/c.heap_sort.autotvin_array_r.dat"
// wrapc file define: "array_out"
#define AUTOTB_TVIN_array_out  "../tv/cdatafile/c.heap_sort.autotvin_array_out.dat"
#define AUTOTB_TVOUT_array_out  "../tv/cdatafile/c.heap_sort.autotvout_array_out.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "array_out"
#define AUTOTB_TVOUT_PC_array_out  "../tv/rtldatafile/rtl.heap_sort.autotvout_array_out.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			array_r_depth = 0;
			array_out_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{array_r " << array_r_depth << "}\n";
			total_list << "{array_out " << array_out_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int array_r_depth;
		int array_out_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define heap_sort AESL_ORIG_DUT_heap_sort
extern void heap_sort (
int array[40],
int array_out[40]);
#undef heap_sort

void heap_sort (
int array[40],
int array_out[40])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "array_out"
		aesl_fh.read(AUTOTB_TVOUT_PC_array_out, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_array_out, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_array_out, AESL_token); // data

			sc_bv<32> *array_out_pc_buffer = new sc_bv<32>[40];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'array_out', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'array_out', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					array_out_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_array_out, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_array_out))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: array_out
				{
					// bitslice(31, 0)
					// {
						// celement: array_out(31, 0)
						// {
							sc_lv<32>* array_out_lv0_0_39_1 = new sc_lv<32>[40];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: array_out(31, 0)
						{
							// carray: (0) => (39) @ (1)
							for (int i_0 = 0; i_0 <= 39; i_0 += 1)
							{
								if (&(array_out[0]) != NULL) // check the null address if the c port is array or others
								{
									array_out_lv0_0_39_1[hls_map_index++].range(31, 0) = sc_bv<32>(array_out_pc_buffer[hls_map_index].range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: array_out(31, 0)
						{
							// carray: (0) => (39) @ (1)
							for (int i_0 = 0; i_0 <= 39; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : array_out[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : array_out[0]
								// output_left_conversion : array_out[i_0]
								// output_type_conversion : (array_out_lv0_0_39_1[hls_map_index++]).to_uint64()
								if (&(array_out[0]) != NULL) // check the null address if the c port is array or others
								{
									array_out[i_0] = (array_out_lv0_0_39_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] array_out_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "array_r"
		char* tvin_array_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_array_r);

		// "array_out"
		char* tvin_array_out = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_array_out);
		char* tvout_array_out = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_array_out);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_array_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_array_r, tvin_array_r);

		sc_bv<32>* array_r_tvin_wrapc_buffer = new sc_bv<32>[40];

		// RTL Name: array_r
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: array(31, 0)
				{
					// carray: (0) => (39) @ (1)
					for (int i_0 = 0; i_0 <= 39; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : array[0]
						// regulate_c_name       : array
						// input_type_conversion : array[i_0]
						if (&(array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> array_tmp_mem;
							array_tmp_mem = array[i_0];
							array_r_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = array_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 40; i++)
		{
			sprintf(tvin_array_r, "%s\n", (array_r_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_array_r, tvin_array_r);
		}

		tcl_file.set_num(40, &tcl_file.array_r_depth);
		sprintf(tvin_array_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_array_r, tvin_array_r);

		// release memory allocation
		delete [] array_r_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_array_out, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_array_out, tvin_array_out);

		sc_bv<32>* array_out_tvin_wrapc_buffer = new sc_bv<32>[40];

		// RTL Name: array_out
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: array_out(31, 0)
				{
					// carray: (0) => (39) @ (1)
					for (int i_0 = 0; i_0 <= 39; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : array_out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : array_out[0]
						// regulate_c_name       : array_out
						// input_type_conversion : array_out[i_0]
						if (&(array_out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> array_out_tmp_mem;
							array_out_tmp_mem = array_out[i_0];
							array_out_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = array_out_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 40; i++)
		{
			sprintf(tvin_array_out, "%s\n", (array_out_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_array_out, tvin_array_out);
		}

		tcl_file.set_num(40, &tcl_file.array_out_depth);
		sprintf(tvin_array_out, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_array_out, tvin_array_out);

		// release memory allocation
		delete [] array_out_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_heap_sort(array, array_out);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_array_out, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_array_out, tvout_array_out);

		sc_bv<32>* array_out_tvout_wrapc_buffer = new sc_bv<32>[40];

		// RTL Name: array_out
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: array_out(31, 0)
				{
					// carray: (0) => (39) @ (1)
					for (int i_0 = 0; i_0 <= 39; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : array_out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : array_out[0]
						// regulate_c_name       : array_out
						// input_type_conversion : array_out[i_0]
						if (&(array_out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> array_out_tmp_mem;
							array_out_tmp_mem = array_out[i_0];
							array_out_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = array_out_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 40; i++)
		{
			sprintf(tvout_array_out, "%s\n", (array_out_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_array_out, tvout_array_out);
		}

		tcl_file.set_num(40, &tcl_file.array_out_depth);
		sprintf(tvout_array_out, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_array_out, tvout_array_out);

		// release memory allocation
		delete [] array_out_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "array_r"
		delete [] tvin_array_r;
		// release memory allocation: "array_out"
		delete [] tvin_array_out;
		delete [] tvout_array_out;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

