// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module heap_sort_swap_hw (
        x_read,
        y_read,
        ap_return_0,
        ap_return_1
);


input  [31:0] x_read;
input  [31:0] y_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

assign ap_return_0 = y_read;

assign ap_return_1 = x_read;

endmodule //heap_sort_swap_hw
