// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xheap_sort.h"

extern XHeap_sort_Config XHeap_sort_ConfigTable[];

XHeap_sort_Config *XHeap_sort_LookupConfig(u16 DeviceId) {
	XHeap_sort_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHEAP_SORT_NUM_INSTANCES; Index++) {
		if (XHeap_sort_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHeap_sort_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHeap_sort_Initialize(XHeap_sort *InstancePtr, u16 DeviceId) {
	XHeap_sort_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHeap_sort_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHeap_sort_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

