// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xinsertion_sort.h"

extern XInsertion_sort_Config XInsertion_sort_ConfigTable[];

XInsertion_sort_Config *XInsertion_sort_LookupConfig(u16 DeviceId) {
	XInsertion_sort_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XINSERTION_SORT_NUM_INSTANCES; Index++) {
		if (XInsertion_sort_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XInsertion_sort_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XInsertion_sort_Initialize(XInsertion_sort *InstancePtr, u16 DeviceId) {
	XInsertion_sort_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XInsertion_sort_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XInsertion_sort_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

