// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XINSERTION_SORT_H
#define XINSERTION_SORT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xinsertion_sort_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XInsertion_sort_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XInsertion_sort;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XInsertion_sort_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XInsertion_sort_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XInsertion_sort_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XInsertion_sort_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XInsertion_sort_Initialize(XInsertion_sort *InstancePtr, u16 DeviceId);
XInsertion_sort_Config* XInsertion_sort_LookupConfig(u16 DeviceId);
int XInsertion_sort_CfgInitialize(XInsertion_sort *InstancePtr, XInsertion_sort_Config *ConfigPtr);
#else
int XInsertion_sort_Initialize(XInsertion_sort *InstancePtr, const char* InstanceName);
int XInsertion_sort_Release(XInsertion_sort *InstancePtr);
#endif

void XInsertion_sort_Start(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_IsDone(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_IsIdle(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_IsReady(XInsertion_sort *InstancePtr);
void XInsertion_sort_EnableAutoRestart(XInsertion_sort *InstancePtr);
void XInsertion_sort_DisableAutoRestart(XInsertion_sort *InstancePtr);

u32 XInsertion_sort_Get_array_r_BaseAddress(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_r_HighAddress(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_r_TotalBytes(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_r_BitWidth(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_r_Depth(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Write_array_r_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length);
u32 XInsertion_sort_Read_array_r_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length);
u32 XInsertion_sort_Write_array_r_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length);
u32 XInsertion_sort_Read_array_r_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length);
u32 XInsertion_sort_Get_array_out_BaseAddress(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_out_HighAddress(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_out_TotalBytes(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_out_BitWidth(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Get_array_out_Depth(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_Write_array_out_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length);
u32 XInsertion_sort_Read_array_out_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length);
u32 XInsertion_sort_Write_array_out_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length);
u32 XInsertion_sort_Read_array_out_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length);

void XInsertion_sort_InterruptGlobalEnable(XInsertion_sort *InstancePtr);
void XInsertion_sort_InterruptGlobalDisable(XInsertion_sort *InstancePtr);
void XInsertion_sort_InterruptEnable(XInsertion_sort *InstancePtr, u32 Mask);
void XInsertion_sort_InterruptDisable(XInsertion_sort *InstancePtr, u32 Mask);
void XInsertion_sort_InterruptClear(XInsertion_sort *InstancePtr, u32 Mask);
u32 XInsertion_sort_InterruptGetEnabled(XInsertion_sort *InstancePtr);
u32 XInsertion_sort_InterruptGetStatus(XInsertion_sort *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
