// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xinsertion_sort.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XInsertion_sort_CfgInitialize(XInsertion_sort *InstancePtr, XInsertion_sort_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XInsertion_sort_Start(XInsertion_sort *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL) & 0x80;
    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XInsertion_sort_IsDone(XInsertion_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XInsertion_sort_IsIdle(XInsertion_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XInsertion_sort_IsReady(XInsertion_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XInsertion_sort_EnableAutoRestart(XInsertion_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XInsertion_sort_DisableAutoRestart(XInsertion_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XInsertion_sort_Get_array_r_BaseAddress(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE);
}

u32 XInsertion_sort_Get_array_r_HighAddress(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH);
}

u32 XInsertion_sort_Get_array_r_TotalBytes(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1);
}

u32 XInsertion_sort_Get_array_r_BitWidth(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XINSERTION_SORT_AXILITES_WIDTH_ARRAY_R;
}

u32 XInsertion_sort_Get_array_r_Depth(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XINSERTION_SORT_AXILITES_DEPTH_ARRAY_R;
}

u32 XInsertion_sort_Write_array_r_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XInsertion_sort_Read_array_r_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XInsertion_sort_Write_array_r_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XInsertion_sort_Read_array_r_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i);
    }
    return length;
}

u32 XInsertion_sort_Get_array_out_BaseAddress(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE);
}

u32 XInsertion_sort_Get_array_out_HighAddress(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH);
}

u32 XInsertion_sort_Get_array_out_TotalBytes(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1);
}

u32 XInsertion_sort_Get_array_out_BitWidth(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XINSERTION_SORT_AXILITES_WIDTH_ARRAY_OUT;
}

u32 XInsertion_sort_Get_array_out_Depth(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XINSERTION_SORT_AXILITES_DEPTH_ARRAY_OUT;
}

u32 XInsertion_sort_Write_array_out_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XInsertion_sort_Read_array_out_Words(XInsertion_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XInsertion_sort_Write_array_out_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XInsertion_sort_Read_array_out_Bytes(XInsertion_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XINSERTION_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i);
    }
    return length;
}

void XInsertion_sort_InterruptGlobalEnable(XInsertion_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_GIE, 1);
}

void XInsertion_sort_InterruptGlobalDisable(XInsertion_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_GIE, 0);
}

void XInsertion_sort_InterruptEnable(XInsertion_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_IER);
    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_IER, Register | Mask);
}

void XInsertion_sort_InterruptDisable(XInsertion_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_IER);
    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_IER, Register & (~Mask));
}

void XInsertion_sort_InterruptClear(XInsertion_sort *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XInsertion_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_ISR, Mask);
}

u32 XInsertion_sort_InterruptGetEnabled(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_IER);
}

u32 XInsertion_sort_InterruptGetStatus(XInsertion_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XInsertion_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XINSERTION_SORT_AXILITES_ADDR_ISR);
}

