// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBUBBLE_SORT_H
#define XBUBBLE_SORT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbubble_sort_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XBubble_sort_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XBubble_sort;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBubble_sort_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBubble_sort_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBubble_sort_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBubble_sort_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBubble_sort_Initialize(XBubble_sort *InstancePtr, u16 DeviceId);
XBubble_sort_Config* XBubble_sort_LookupConfig(u16 DeviceId);
int XBubble_sort_CfgInitialize(XBubble_sort *InstancePtr, XBubble_sort_Config *ConfigPtr);
#else
int XBubble_sort_Initialize(XBubble_sort *InstancePtr, const char* InstanceName);
int XBubble_sort_Release(XBubble_sort *InstancePtr);
#endif

void XBubble_sort_Start(XBubble_sort *InstancePtr);
u32 XBubble_sort_IsDone(XBubble_sort *InstancePtr);
u32 XBubble_sort_IsIdle(XBubble_sort *InstancePtr);
u32 XBubble_sort_IsReady(XBubble_sort *InstancePtr);
void XBubble_sort_EnableAutoRestart(XBubble_sort *InstancePtr);
void XBubble_sort_DisableAutoRestart(XBubble_sort *InstancePtr);

u32 XBubble_sort_Get_array_r_BaseAddress(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_r_HighAddress(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_r_TotalBytes(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_r_BitWidth(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_r_Depth(XBubble_sort *InstancePtr);
u32 XBubble_sort_Write_array_r_Words(XBubble_sort *InstancePtr, int offset, int *data, int length);
u32 XBubble_sort_Read_array_r_Words(XBubble_sort *InstancePtr, int offset, int *data, int length);
u32 XBubble_sort_Write_array_r_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length);
u32 XBubble_sort_Read_array_r_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length);
u32 XBubble_sort_Get_array_out_BaseAddress(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_out_HighAddress(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_out_TotalBytes(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_out_BitWidth(XBubble_sort *InstancePtr);
u32 XBubble_sort_Get_array_out_Depth(XBubble_sort *InstancePtr);
u32 XBubble_sort_Write_array_out_Words(XBubble_sort *InstancePtr, int offset, int *data, int length);
u32 XBubble_sort_Read_array_out_Words(XBubble_sort *InstancePtr, int offset, int *data, int length);
u32 XBubble_sort_Write_array_out_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length);
u32 XBubble_sort_Read_array_out_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length);

void XBubble_sort_InterruptGlobalEnable(XBubble_sort *InstancePtr);
void XBubble_sort_InterruptGlobalDisable(XBubble_sort *InstancePtr);
void XBubble_sort_InterruptEnable(XBubble_sort *InstancePtr, u32 Mask);
void XBubble_sort_InterruptDisable(XBubble_sort *InstancePtr, u32 Mask);
void XBubble_sort_InterruptClear(XBubble_sort *InstancePtr, u32 Mask);
u32 XBubble_sort_InterruptGetEnabled(XBubble_sort *InstancePtr);
u32 XBubble_sort_InterruptGetStatus(XBubble_sort *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
