// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbubble_sort.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBubble_sort_CfgInitialize(XBubble_sort *InstancePtr, XBubble_sort_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBubble_sort_Start(XBubble_sort *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL) & 0x80;
    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBubble_sort_IsDone(XBubble_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBubble_sort_IsIdle(XBubble_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBubble_sort_IsReady(XBubble_sort *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBubble_sort_EnableAutoRestart(XBubble_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XBubble_sort_DisableAutoRestart(XBubble_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XBubble_sort_Get_array_r_BaseAddress(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE);
}

u32 XBubble_sort_Get_array_r_HighAddress(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH);
}

u32 XBubble_sort_Get_array_r_TotalBytes(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1);
}

u32 XBubble_sort_Get_array_r_BitWidth(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBUBBLE_SORT_AXILITES_WIDTH_ARRAY_R;
}

u32 XBubble_sort_Get_array_r_Depth(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBUBBLE_SORT_AXILITES_DEPTH_ARRAY_R;
}

u32 XBubble_sort_Write_array_r_Words(XBubble_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XBubble_sort_Read_array_r_Words(XBubble_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XBubble_sort_Write_array_r_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XBubble_sort_Read_array_r_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_R_BASE + offset + i);
    }
    return length;
}

u32 XBubble_sort_Get_array_out_BaseAddress(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE);
}

u32 XBubble_sort_Get_array_out_HighAddress(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH);
}

u32 XBubble_sort_Get_array_out_TotalBytes(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1);
}

u32 XBubble_sort_Get_array_out_BitWidth(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBUBBLE_SORT_AXILITES_WIDTH_ARRAY_OUT;
}

u32 XBubble_sort_Get_array_out_Depth(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBUBBLE_SORT_AXILITES_DEPTH_ARRAY_OUT;
}

u32 XBubble_sort_Write_array_out_Words(XBubble_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XBubble_sort_Read_array_out_Words(XBubble_sort *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XBubble_sort_Write_array_out_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XBubble_sort_Read_array_out_Bytes(XBubble_sort *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_HIGH - XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XBUBBLE_SORT_AXILITES_ADDR_ARRAY_OUT_BASE + offset + i);
    }
    return length;
}

void XBubble_sort_InterruptGlobalEnable(XBubble_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_GIE, 1);
}

void XBubble_sort_InterruptGlobalDisable(XBubble_sort *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_GIE, 0);
}

void XBubble_sort_InterruptEnable(XBubble_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_IER);
    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_IER, Register | Mask);
}

void XBubble_sort_InterruptDisable(XBubble_sort *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_IER);
    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_IER, Register & (~Mask));
}

void XBubble_sort_InterruptClear(XBubble_sort *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBubble_sort_WriteReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_ISR, Mask);
}

u32 XBubble_sort_InterruptGetEnabled(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_IER);
}

u32 XBubble_sort_InterruptGetStatus(XBubble_sort *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBubble_sort_ReadReg(InstancePtr->Axilites_BaseAddress, XBUBBLE_SORT_AXILITES_ADDR_ISR);
}

